### ISSUE TITLE
please post source code and files for this project

### ISSUE THREAD

**Issue by gtr667gwy45** [Aimoshe/AI-Aimbot#1]
@Aimoshe  please would you mind kindly post source code and files for this project? please thank you very much i really appreciate it

**Comment by Aimoshe** [comment]
This project is provided for educational purpose.
If you want the source code, please contact me via your university email.
You can see my email address in my profile bio.

**Comment by gtr667gwy45** [comment]
@Aimoshe  Yes, sure. I emailed you. Please kindly look for my email. Thank you.
